<epos-print xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print">
<text align="center"/>
<feed/>
<image width="300" height="191" color="color_1" mode="mono">AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAr////6gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAFf//////0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAr/////////oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAX//////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAC/////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAABf/////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAA///////////////+gAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAX////////////////AAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAP/////////////////4AAAAAAAAAAAAAAAAAAAAAAAAAAfAAAAH//////1AAFX///////0AAAAAAAAAAAAAAAAAAAAAAAAAA+AAAD/////6oAAAACv//////+AAAAAAAAAAAAAAAAAAAAAAAAABwAABf////wAAAAAAAAX/////8AAAAAAAAAAAAAAAAAAAAAAAAAHgAA/////oAAAAAAAAAL/////+gAAAAAAAAAAAAAAAAAAAAAAAAPAAH////AAAAAAAAAAAAX/////AAAAAAAAAAAAAAAAAAAAAAAAA+AD///+gAAAAAAAAAAAAL/////gAAAAAAAAAAAAAAAAAAAAAAAB8Af//9AAAAAAAAAAAAAABf////AAAAAAAAAAAAAAAAAAAAAAAAD4P///gAAAAAAAAAAAAAAAv////gAAAAAAAAAAAAAAAAAAAAAAAH3///AAAAAAAAAAAAAAAAAX////AAAAAAAAAAAAAAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAAP////gAAAAAAAAAAAAAAAAAAAAAAB///wAAAAAAAAAAAAAAAAAAH////AAAAAAAAAAAAAAAAAAAAAAAH//+AAAAAAAAAAAAAAAAAAAP////gAAAAAAAAAAAAAAAAAAAAAAf//AAAAAAAAAAAAAAAAAAAAH////AAAAAAAAAAAAAAAAAAAAAAP//oAAAAAAAAAAAAAAAAAAAAD///+AAAAAAAAAAAAAAAAAAAAAB//0AAAAAAAAAAAAAAAAAAAAAB///8AAAAAAAAAAAAAAAAAAAAA///AAAAAAAAAAAAAAAAAAAAAAD///+AAAAAAAAAAAAAAAAAAAAH//8AAAAAAAAAAAAAAAAAAAAAAB///8AAAAAAAAAAAAAAAAAAAA///4AAAAAAAAAAAAAAAAAAAAAAC///+AAAAAAAAAAAAAAAAAAAH/9fwAAAAAAAAAAAAAAAAAAAAAAAf//8AAAAAAAAAAAAAAAAAAD//g/gAAAAAAAAAAAAAAAAAAAAAAA///8AAAAAAAAAAAAAAAAAAf/wB+AAAAAAAAAAAAAAAAAAAAAAAAf//4AAAAAAAAAAAAAAAAAH/+AD+AAAAAAAAAAAAAAAAAAAAAAAA///4AAAAAAAAAAAAAAAAA//wAH4AAAAAAAAAAAAAAAAAAAAAAAB///wAAAAAAAAAAAAAAAAP/8AAP4AAAAAAAAAAAAAAAAAAAAAAAP///gAAAAAAAAAAAAAAAB//AAAfAAAAAAAAAAAAAAAAAAAAAAAB////AAAAAAAAAAAAAAAAP/4AAA/AAAAAAAAAAAAAAAAAAAAAAAP////gAAAAAAAAAAAAAAB/8AAAB8AAAAAAAAAAAAAAAAAAAAAAB/////AAAAAAAAAAAAAAAf/gAAAD+AAAAAAAAAAAAAAAAAAAAAAP////+AAAAAAAAAAAAAAB/8AAAAH4AAAAAAAAAAAAAAAAAAAAAB//3//8AAAAAAAAAAAAAA//AAAAAP4AAAAAAAAAAAAAAAAAAAAAP/+D//4AAAAAAAAAAAAAH/wAAAAAfgAAAAAAAAAAAAAAAAAAAAB//AF//wAAAAAAAAAAAAA/+AAAAAA/gAAAAAAAAAAAAAAAAAAAAP/4AP//wAAAAAAAAAAAAH/wAAAAAB/AAAAAAAAAAAAAAAAAAAAB//AAH//AAAAAAAAAAAAA/+AAAAAAD+AAAAAAAAAAAAAAAAAAAAP/4AAP//AAAAAAAAAAAAH/AAAAAAAH8AAAAAAAAAAAAAAAAAAAAf8AAAf/8AAAAAAAAAAAA/6AAAAAAAP8AAAAAAAAAAAAAAAAAAAD/oAAA//+AAAAAAAAAAAH/AAAAAAAAfwAAAAAAAAAAAAAAAAAAAf8AAAB//8AAAAAAAAAAA/4AAAAAAAA/4AAAAAAAAAAAAAAAAAAD/gAAAD//4AAAAAAAAAAH/AAAAAAAAB/gAAAAAAAAAAAAAAAAAAP8AAAAH//wAAAAAAAAAB/4AAAAAAAAD/gHgAAAAAAAAAAAAAAAB/4AAAAP//gAAAAAAAAAH/AAAAAAAAAH/AfAAAAAAAAAAAAAAAAH+AAAAAP//AAAAAAAAAA/4AAAAAAAAAP+D/AAAAAAAAAAAAAAAA/4AAAAAf/+AAAAAAAAAH+AAAAAAAAAAf8H8AAAAAAAAAAAAAAAD/AAAAAAf/4AAAAAAAAB/wAAAAAACgAA/6f4AAAAAAAAAAAAAAAP4AAAAAA//4AAAAAAAAH8AAAAAAAPAAA/B/gAAAAAAAAAAAAAAB/gAAAAAB//gAAAAAAAA/wAAAAAAA+AAB4D+AAAAAAAAAAAAAAAH+AAAAAAD//AAAAAAAAH8AAAAAAAB8AAAAfwAAAAAAAAAAAAAAAfwAAAAAAH/8AAAAAAAA/wAAAAAAAH4AAAA/gAAAAAAAAAAAAAAD/AAAAAAAP/8AAAAAAAH8AAAAAAAAfwAAAD8AAAAAAAAAAAAAAAH8AAAAAAAf/wAAAAAAA/gAAAAAAAB+AAAAP4AAAAAAAAAAAAAAA/gAAAAfgA//gAAAAAAH8AAAAAAAAHwAAAB/AAAAAAAAAAAAAAAB+AAAAB+AB//AAAAAAA/wAAAAAAAAfgAAAD8AAAAAAAAAAAAAAAP4AAAAP4AD/+AAAAAAH8AAAAAAAAB8AAAAfwAAAAAAAAAAAAAAAfAAAAAfgAH/8AAAAAA/wAAAAAAAAHwAAAA/AvgAAAAAAAAAAAAD+AAAAD+AAP/4AAAAAH8AAAAAAAAAfAAAAH8H/AAAAAAAAAAAAAHwAAAAH4AAf/wAAAAA/wAAAAAAAAA+AAAAP//+AAAAAAAAAAAAA/gAAAAKAAB//gAAAAB+AAAAAAAAAHwAAAB///4AAAAAAAAAAAAB8AAAAAAAAH//AAAAAfwAAAAAAAAAfgAAAD///gAAAAAAAAAAAAD4AAAAAAAA//+AAAAB+AAAAAAAAAB/AAAAf//8UAAAAAAAAAAAAPAAAAAAAAX//8AAAAP4AAAAAAAAA/+AAAD///46AAAAAAAAAAAA+AAAAAAAP///wAAAB/AAAAAAAAAX/wAAAP//8D8AAAAAAAAAAABwAAAAAAB///8AAAAP4AAAAAAAAP//gAAD///wP+gAAAAAAAAAAHgAAAAAA////gAAAA/AAAAAAAAF//8AAAf//8B//AAAAAAAAAAAMAAAAAAf///8AAAAP4AAAAAAAD///wAAP///gP//oAAAAAAAAAA4AAAAAP////gAAAAfAAAAAAABf0H8AAB1//8Af//0AAAAAAAAABAAAAAF////wAAAAD8AAAAAAC/+AfgAAOD//gD///+AAAAAAAAAGAAAAD////+AAAAAfAAAAAAB//AB8AAHAH/4AB////AAAAAAAAAAAAAB/////AAAAAD+AAAAAA//4APwAD4A//AAD////6AAAAAAAAgAAD/////gAAAAAPwAAAAAH/8AAfAAcAB/wAAB////9AAAAAAAAAAB/////wAAAAAA+AAAAAAP/gAD4ADgAP+AAAA/////6AAAAAAAAL/////+AAAAAAHwAAAAAAfQAAfgB4AA/wAAAAf/////QAAAAABX/////8AAAAAAA/AAAAAAA4AAD+A+AAD+AAAAAv//////+qqqv///////gAAAAAAD8AAAAAAAAAAf4HwAAPwAAAAAH/////////////////AAAAAAAAPgAAAAAAAAAD/r6AAL+AAAAAAL////////////////oAAAAAAAB8AAAAAAAAAAH/9AAB/8AAAAAABf//////////////wAAAAAAAAPwAAAAAAAAAD//gAL//+AAAAAAA//////////////4AAAAAAAAAeAAAAAAAAAAf/8AA////UAAAAAAH////////////wAAAAAAAAAD4AAAAAAAAAD/+gAD///////7oAAD///////////4AAAAAAAAAAPAAAAAAAAAAf/wAAH/////////AAAX////////9QAAAAAAAAAAA8AAAAAAAAAD/+AAAP/////////+gAC///////+gAAAAAAAAAAAHwAAAAAAAAAf/4AAA/f/////////UAABf///9QAAAAAAAAAAAAAOAAAAAAAAAP//gAAPgf//////////6AAAqqgAAAAAAAAAAAAAAB4AAAAAAAAB//+AABwA///////////8AAAAAAAAAAAAAAAAAAAAHgAAAAACAAP/74AAOgD7//////////4AAAAAAAAAAAAAAAAAAAAeAAAAgAcAF//HgABwAPB//////////AAAAAAAAAAAAAAAAAAAAA4AAAD4LgA//4OAA+AA+A/////////gAAAAAAAAAAAAAAAAAAAAHAAAAH38AH//AYAHAADwAf///////wAAAAAAAAAAAAAAAAAAAAAOAAAAP/4D//+DgA4AAPgA///////6AAAAAAAAAAAAAAAAAAAAAAcAAAAf8AP/9wGAEAAA8AAf/////wAAAAAAAAAAAAAAAAAAAAAADgAAAB/wB/+AD4AAAAD4AA/////4AAAAAAAAAAAAAAAAAAAAAAAHAAAAD8AH/wA/wAAAAPAAAf///0AAAAAAAAAAAAAAAAAAAAAAAAOAAAAPgAP+AD/gAAAA+AAA///+AAAAAAAAAAAAAAAAAAAAAAAAAcAAAB8AA/wAH8AAAADwAAAf//AAAAAAAAAAAAAAAAAAAAAAAAAA4AAAvgAB+AAf4AAAAPgAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAB8AAHwAAAAAB/AAAAA+AAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAD+oL+AAAAAAD+AAAAP4AAAAL+AAAAAAAAAAAAAAAAAAAAAAAAAAB///AAAAAAAPwAAAF/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv/gAAAAAAA+AAB//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAD//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgAAP//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVEAAAAAAAAAAAAAAAAAAAAAAAAAAXUAAAAAAAAAAAAAAAAAAAD//gAAAAAAAAAAAAAAAAAAAAAAAAAP/+AAAAAAAAAAAAAAAAAAAfXeAAAAAAAAAAAAAAAAAAAAAAAAAF//8AAAVAAAAAAAAAAAAAAPoA4AA/+AA+AD//gAD4AA4D/wAAAA+i/4AA//4AH+AAAPg///AB8AAAAB/wAHwAf/8AAHgABgP/AAAAHwAfAAH//wAf8AAB8B+RcAPgAAAAD+AAOAD4i4AA+AAOAP4AAAD4AB4AD+r/gA/gAADgD4AgAeAAAAAHwABwAcAAAAB4AAQAfAAAAPAAHAAcAF/AAfAAAcAHgAAD4AAAAA/AADAD4AAAAPgADgD4AAAD4AAOAD4AP+AB+AADgA+AAAH0AAAAB8AAcAfAAAAAeAAEAHwAAAHAAAAAcAAH8AH4AAEAB4AAAP+gAAAPwAAgB+AAAAD4AA4A+AAAA8AAAADwAA/4APgAA4Af/4AAf/0AAAfAAHAH8AAAAHgABAB8AAAHgAAAAcAAA/AAfAAHAA+BAAAv//oAD8AAMAP/oAAA+AAOAPgAAA+AAAAD4AAD+AD+AAcAD4AAAAF//wAHwABwAH/1AAB4AAYAfAAAHwAAAAPAAAH4AHwABgAHgAAAAC//4A/AACAAD//oAPgADgD4AAAeAAAAA4AAAfgAPgAOAA+AAAAAAf/wB8AAcAAB//wAeAAEAHwAAB4AAAAHgAAB/AA+AAwAB4AAAAAAP/gPwAAwAAA//4D4AA4A+AAAPgAAAA+AAAD4AD8ADgAPgAAAAAAH+AfAAHAAAAH/gHgABAB8AAAeAAAABwAAAPwAHwAcAAeAAAAAAAP4D8AAIAAAAP/A+AAOAPgAAD4AAAAPgAAA+AAfgBgAD4AAAAAAAfgHwABwAAAAH8B4AAQAfAAAPAAAAA8AAAD4AB+AGAAHgAAAAAAD+A/AADAAAAAPwPgADgD4AAA+AAAAD4AAAPgAD4A4AA+AAAAAAAHwB8AAcAAAAAfAeAAGAHwAAD4AAAAPAAAA8AAHwDAAB4AAAAAAAfAPwABgAAAAD4D4AA6A+AAAPgAAAA+AAAD4AA/AcAAPgAAAAAAB4AfAAHAAAAAHAHgAXUB8AAA+AAAADwAAAfAAB8BwAAeAAAAAAAPgB+AAYAAAAA8A+APuAPgAAD4AAAAPgAAB4AAD4OAAD4AAAAAAAcAHwABwAAAADwB4BwQAfAAAHwAAAA+AAAHgAAPwgAAHgAAAAAADgAPgAOAAAAAOAPg8DgD4AAA/gAAAD4AAA+AAA/DgAA+AAAAAAAcAA+AAgAAAABwAeHAEAHwAAB8AAAQHwAADwAAB8MAAB4AAAAAADgAD8ADgAAAAOAD74A4A+AAAH4AADwfgAAeAAAP5gAAPgAAAAAAcAAHwAcAAAABwAHvABgB8AAAPwAAHA/AABwAAAfmAAAeAAAAAADgAAPgDgAAAAOAA/4AOAPgAAA/gAD4D+AAeAAAA+4AAD4AAAAAAcAAAfAcAAAABwAD/AAQAfAAAB/AAfAH8ABwAAAB9AAAHgAAAAeLgAAB//gAAA4OAA/4ADgD+AAAD/gL4AP+C+AAAAP8AAA+AAoAB/8AAAB/8AAAH/wAH/AAEA/8AAAB/18AAf/fAAAAAfwAAH5EXwAH+gAAAD+gAAAf8AAP4AA4D/wAAAD/+gAAP/oAAAAA+AAA////AAAAAAAAAAAAAAAAAAAAAAAAAAAAABVAAAAFQAAAAAAAAAAAAAAA==</image>
<feed/>

<text align="left"/>
<text>Does tab work&#9;&#9;&#9;Hello&#10;</text>
<text align="left"/>
<text x="20"/>
<text>This is some text</text>
<text align="right"/>
<text>$10.53&#10;</text>
<text x="20"/>
<text>Here is some more text</text>
<text x="400"/>
<text>$11.11&#10;</text>
<text x="20"/>
<text>Here is a boat ton of text that should wrap like crazy</text>
<text x="400"/>
<text>$100.25&#10;</text>
<feed/>



<feed/>
<cut type="feed"/>

</epos-print>

//Set the end point address
var url = 'http://192.168.2.36/cgi-bin/epos/service.cgi?devid=local_printer&timeout=10000';
//Create an empty print document to check the printer status
var soap = '<?xml version="1.0" encoding="UTF-8"?>';
soap += '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">';'
soap += '<s:Header>';
soap += '<parameter xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print">';
soap += '<devid>local_printer</devid>';
soap += '<timeout>60000</timeout>';
soap += '<printjobid>ABC123</printjobid>';
soap += '</parameter>';
soap += '</s:Header>';
soap += '<s:Body>';
soap += '<epos-print xmlns="http://www.epson-pos.com/schemas/2011/03/epos-print">';
soap += '<text>Hello, World!&#10;</text>';
soap += '<cut />';
soap += '</epos-print>';
soap += '</s:Body>';
soap += '/s:Envelope>';
//Create an XMLHttpRequest object
var xhr = new XMLHttpRequest();
//<Open an XMLHttpRequest object>
xhr.open('POST', url, true);
//<Header settings>
xhr.setRequestHeader('Content-Type', 'text/xml; charset=utf-8');
xhr.setRequestHeader('If-Modified-Since', 'Thu, 01 Jan 1970 00:00:00 GMT');
xhr.setRequestHeader('SOAPAction', '""');
//Set a response reception callback function for checking
xhr.onreadystatechange = function () {
 if (xhr.readyState == 4){
   if (xhr.status == 200){
     var res = xhr.responseXML;
     var success = res.getElementsByTagName('response')[0].getAttribute('success');
     if (!/^(1|true)$/.test(success)) {
       alert('Success');
     }
   }
 }
};
//Send print data
xhr.send(soap);
